# Generated by Django 2.2.5 on 2019-10-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='mida',
            new_name='medida',
        ),
    ]
